repos:
- repo: https://github.com/dbt-checkpoint/dbt-checkpoint
  rev: v1.1.0
  hooks:
  - id: dbt-deps
  - id: dbt-compile
    args: ["--cmd-flags", "++profiles-dir", ".", "++target=staging", "--"]
  - id: check-model-has-description