name: 'analytics' # change in seeds section too
version: '1.0.0'

config-version: 2


# Which context to use in profiles.yml
profile: 'default'


# These configurations specify where dbt should look for different types of files
# These don't typically change
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]


# These don't typically change
target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"