name: Clean BigQuery Staging Environment
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GCP_STAGING_PROJECT: data-sandbox-stage-266217
  DBT_PR_PREFIX: dbt_pr

permissions:
  pull-requests: read
  checks: read
  contents: read

jobs:
  clean_staging_env:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps: 
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.STAGING_ENVIRONMENT_SERVICE_ACC }}'

      - name: 'Setup Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Purge non-PR staging datasets'
        run: |
          function join { local IFS="$1"; shift; echo "$*"; }
          BQ_DATASET_LIST_DUMMY=$(bq ls -n 1 --quiet --project_id $GCP_STAGING_PROJECT | tail +3) # Dummy variable to avoid the first line of the bq -ls command and credentials. The first time this command is run it produces unwanted dialogue.
          BQ_DATASET_LIST=$(bq ls -n 1000 --quiet --project_id $GCP_STAGING_PROJECT | tail +3)
          PR_NUMBERS="$(gh pr list --state open --repo $GITHUB_REPOSITORY --json number --jq '.[].number')"
          GH_LIST_ID=$(join '|' ${PR_NUMBERS[@]})
          for dataset in $BQ_DATASET_LIST
          do
              # If the dataset name contains an opened Pull Request ID, then we do nothing
              if [[ "$dataset" =~ "$DBT_PR_PREFIX""_"${GH_LIST_ID}"_".* ]]; then
                echo "$dataset belongs to open PR"
              # Indicates the last items of the bq -ls header command before the list of datasets
              elif [[ "$dataset" =~ "--------".* ]]; then
                  echo "pass"
              # For all the other datasets
              else
                  echo "Deleting dataset $dataset"
                  bq rm -r -f --project_id=$GCP_STAGING_PROJECT $dataset
              fi
          done