name: SQLFluff lint dbt data models

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - 'models/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  DBT_PROFILES_DIR: ./
  DBT_GOOGLE_BIGQUERY_DATASET: dbt_placeholder_do_not_change

permissions:
  pull-requests: read
  checks: write
  contents: read

jobs:
  sqlfluff-lint-models:
    name: Lint dbt models using SQLFluff
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Setup service account JSON
        run: |
            echo '${{ secrets.STAGING_ENVIRONMENT_SERVICE_ACC }}' > service_account.json
        shell: bash

      - name: Setup dbt profiles YML
        run: |
            echo '${{ secrets.PROFILES_YML }}' > profiles.yml
        shell: bash

      - name: Install dbt and sqlfluff dbt templater
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: dbt deps
        run: |
          dbt deps

      - name: Get changed files
        id: get_file_changes
        uses: tj-actions/changed-files@v41
        with:
          files: models/**
      
      - name: List all changed files
        run: |
          for file in ${{ steps.get_file_changes.outputs.all_changed_files }}; do
            echo "$file was changed"
          done


      - name: Get new and changed .sql files in /models to lint
        id: get_files_to_lint
        shell: bash -l {0}
        run: |
          # Set the command in the $() brackets as an output to use in later steps
          echo "::set-output name=lintees::$(
          # Issue where grep regular expressions don't work as expected on the
          # Github Actions shell, check dbt/models/ folder
          echo \
          $(echo ${{ steps.get_file_changes.outputs.all_changed_files }} |
          tr -s ' ' '\n' |
          grep -E '^models.*[.]sql$' |
          tr -s '\n' ' ')
          )"

      - name: Lint dbt models (console output)
        if: steps.get_files_to_lint.outputs.lintees != ''
        shell: bash -l {0}
        run: |
          sqlfluff lint ${{ steps.get_files_to_lint.outputs.lintees }} --format github-annotation --annotation-level failure --nofail

      - name: Lint dbt models (annotations.json output)
        if: steps.get_files_to_lint.outputs.lintees != ''
        shell: bash -l {0}
        run: |
          sqlfluff lint ${{ steps.get_files_to_lint.outputs.lintees }} --format github-annotation --annotation-level failure --nofail > annotations.json
  
      - name: Annotate
        uses: yuzutech/annotations-action@v0.4.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title: "SQLFluff Lint - Ghost of JDRG"
          input: "./annotations.json"